//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace testTest.Module.BusinessObjects.dbDeneme
{

    [Persistent(@"tbl_firma")]
    public partial class Firma : XPLiteObject
    {
        int ffirm_id;
        [Key]
        [Persistent(@"id")]
        public int firm_id
        {
            get { return ffirm_id; }
            set { SetPropertyValue<int>(nameof(firm_id), ref ffirm_id, value); }
        }
        string ffirma_adi;
        [Size(50)]
        public string firma_adi
        {
            get { return ffirma_adi; }
            set { SetPropertyValue<string>(nameof(firma_adi), ref ffirma_adi, value); }
        }
        string ffirma_tel;
        [Size(50)]
        public string firma_tel
        {
            get { return ffirma_tel; }
            set { SetPropertyValue<string>(nameof(firma_tel), ref ffirma_tel, value); }
        }
    }

}
